name: Deploy to Hugging Face
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to Hugging Face
        run: |
          git clone https://nickynicolson:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/nickynicolson/hp-solanaceae
          cd hp-solanaceae
          cp -r ../* . || true  # Copy all files (Static or Docker)
          # rm oversized files
          rm assets/images/DSC_1245.JPG assets/images/DSC_1260.JPG assets/images/DSC_1292.JPG assets/images/Nicotianoideae/Anthocercideae/Anthoceris/Anthocercis littorea CervantesDSC01312.tif assets/images/Petunioideae/Petunia patagonica KewDSC05345.tif
          git add .
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Update from GitHub" || true
          git push
